@musican = http://localhost:4004/musican

### Get all InstrumentTypes
GET {{musican}}/InstrumentType?$top=50
Accept: application/json

### Get InstrumentType by code (key is 'code')
GET {{musican}}/InstrumentType('VIOL')
Accept: application/json

### Create InstrumentType
POST {{musican}}/InstrumentType
Content-Type: application/json

{
  "code": "HARP",
  "description": "Harp"
}

### Update InstrumentType
PATCH {{musican}}/InstrumentType('VIOL')
Content-Type: application/json

{
  "description": "Violin (updated)"
}

### Delete InstrumentType
DELETE {{musican}}/InstrumentType('HARP')
