# BandService - metadata and service root
@band= http://localhost:4004/odata/v4/band
@musican = http://localhost:4004/odata/v4/musican

### Get $metadata
GET {{band}}/$metadata
Accept: application/xml

### Get service root (entity sets)
GET {{musican}}/$metadata
Accept: application/json
